Repository RIOT-OS/riot-os.org, pull requests merged in 2021-11, with the labels that each got.

#92 There is no such thing as freenode
  index.html
Labels: content

#94 README: add deployment workflow badge
  README.md
Labels: documentation

#95 faq: update GPG key for security mailing list
  _faqs/faq-06.md
  assets/keys/security.asc
Labels: enhancement, content

#98 Gemfile: add webrick dependency
  Gemfile
Labels: bug, CI / Tooling

#99 social-media: fix Discourse logo
  _includes/social-media.html
Labels: bug
