Repository RIOT-OS/riot-os.org, pull requests merged in 2021-04, with the labels that each got.

#72 users: add SSV GmbH
  _data/companies.yml
  _use_cases/ssv.md
  assets/img/companies/ssv-logo.svg
  assets/img/use-cases/user-photos/Juergen-Fitschen.jpg
Labels: content

#77 index: fix link to Embedded Unit
  index.html
Labels: bug, content

#78 branding: fix sample sizes and use vector logo
  _sass/pages/branding.scss
  assets/css/main.scss
  assets/img/riot-logo.svg
  branding.html
Labels: layout
