Repository RIOT-OS/riot-os.org, pull requests merged in 2021-03, with the labels that each got.

#21 index/blog: list authors
  _layouts/blog.html
  _posts/2020-12-31-test.md
  index.html
Labels: enhancement

#24 faq: clarify which reference to use when citing RIOT
  _faqs/faq-12.md
  assets/pdfs/riot-ieeeiotjournal-2018.pdf
Labels: enhancement

#32 blog: fix author social badges links
  _layouts/blog.html
Labels: bug

#17 refactor riot-os.org data update
  .github/workflows/deployment.yml
  .github/workflows/get_contributors.js
  .gitignore
  Makefile
  README.md
  _config.yml
  _config_development.yml
  _config_production.yml
  _data/contributors.json
  _data/contributors.json.dist
  _data/riot_boards.yml
  _data/riot_boards.yml.dist
  _data/riot_cpus.yml
  _data/riot_cpus.yml.dist
  _data/riot_drivers.csv.dist
  _data/riot_drivers.json.dist
  _data/riot_drivers_cats.csv.dist
  _data/riot_stats.yml.dist
  _tools/requirements.txt
  _tools/riot-boards.sh
  _tools/riot-contributors.py
  _tools/riot-cpus.sh
  _tools/riot-drivers-cats.sh
  _tools/riot-drivers.sh
  _tools/riot-stats.sh
  drivers.html
Labels: enhancement

#15 gh_actions: add Surge PR preview
  .github/workflows/pr_preview.yml
Labels: enhancement

#35 gh_actions/pr_preview: split into two workflows
  .github/workflows/pr_preview.yml
  .github/workflows/preview_pr.yml
  .github/workflows/receive_pr.yml
Labels: bug

#33 index: fix contributors counter
  index.html
Labels: bug

#37 [RFC] includes/header: include external icon and change target
  _includes/header.html
  _sass/components/navbar.scss
Labels: layout

#38 accessibility: fix issues pointed out by webaccessibility.com
  _includes/footer.html
  _includes/header.html
  _includes/social-media.html
  _includes/use-cases-carousel.html
  _layouts/blog.html
  _layouts/use-case.html
  branding.html
  community.html
  contributors.html
  index.html
Labels: enhancement

#42 users: add Locha story
  _includes/use-cases-carousel.html
  _includes/use-cases-logo-wall.html
  _layouts/use-case.html
  _sass/pages/use-case.scss
  _use_cases/use-locha.md
  assets/img/use-cases/logos/lochamesh-logo.svg
  assets/img/use-cases/user-photos/Jean-Pierre-Dudey.jpg
Labels: content, enhancement, layout

#44 users: remove dummy files and add links to logo wall
  _includes/use-cases-carousel.html
  _includes/use-cases-logo-wall.html
  _layouts/use-case.html
  _use_cases/locha.md
  _use_cases/use-01.md
  _use_cases/use-02.md
  _use_cases/use-03.md
  _use_cases/use-04.md
Labels: enhancement, layout

#45 users: add wolfSSL
  _use_cases/wolfssl.md
  assets/img/use-cases/logos/wolfssl-logo.jpg
  assets/img/use-cases/user-photos/daniele-lacamera.jpg
Labels: content

#46 button: give learn-more button consistent look globally, add button t…
  _includes/use-cases-carousel.html
  _sass/_general.scss
Labels: layout

#47 Logo-wall: center logos and open links in new tab
  _includes/use-cases-logo-wall.html
Labels: layout

#39 Rework site data generation
  .gitignore
  Makefile
  README.md
  _config.yml
  _data/contributors.json.dist
  _data/riot_boards.yml.dist
  _data/riot_cpus.yml.dist
  _data/riot_drivers.csv.dist
  _data/riot_drivers.json.dist
  _data/riot_drivers_cats.csv.dist
  _data/riot_stats.yml.dist
  _tools/default_data.py
  _tools/fetch_riot_data.py
  _tools/riot-boards.sh
  _tools/riot-contributors.py
  _tools/riot-cpus.sh
  _tools/riot-drivers-cats.sh
  _tools/riot-drivers.sh
  _tools/riot-stats.sh
  community.html
  contributors.html
  drivers.html
  index.html
Labels: CI / Tooling

#48 use cases: add Savoir-faire Linux logo
  _use_cases/savoir-faire-linux.md
  assets/img/use-cases/logos/savoir-faire-linux-logo.svg
Labels: content

#50 assets/logos: add dimensions to savoir-faire
  assets/img/use-cases/logos/savoir-faire-linux-logo.svg
Labels: bug, content

#54 users: add Sapienza University of Rome
  _use_cases/sapienza-university.md
  assets/img/use-cases/logos/sapienza-university.jpg
  assets/img/use-cases/user-photos/Ioannis-Chatzigiannak.jpg
Labels: content

#53 includes/use_cases_carousel: limit quote lines
  _includes/use-cases-carousel.html
  _layouts/use-case.html
  _sass/components/use-cases-carousel.scss
Labels: layout

#51 users: add Continental
  _use_cases/continental.md
  assets/img/use-cases/logos/continental-logo.svg
  assets/img/use-cases/user-photos/vincent-dupont.jpg
Labels: content

#57 includes/use-cases-carousel: change anchor to 'use-cases'
  _includes/header.html
  _includes/use-cases-carousel.html
  _sass/components/use-cases-carousel.scss
Labels: cleanup

#60 _use_cases: split companies from use cases
  .gitignore
  README.md
  _data/companies.yml
  _includes/use-cases-carousel.html
  _includes/use-cases-logo-wall.html
  _layouts/use-case.html
  _use_cases/continental.md
  _use_cases/locha.md
  _use_cases/sapienza-university.md
  _use_cases/wolfssl.md
  assets/img/companies/continental-logo.svg
  assets/img/companies/lochamesh-logo.svg
  assets/img/companies/sapienza-university.jpg
  assets/img/companies/savoir-faire-linux-logo.svg
  assets/img/companies/wolfssl-logo.jpg
Labels: content

#58 layouts/use-case: add previous and next links
  _layouts/use-case.html
  _sass/pages/use-case.scss
  _use_cases/savoir-faire-linux.md
Labels: layout

#62 assets/companies: scale down Locha and wolffSSL logos
  assets/img/companies/lochamesh-logo.svg
  assets/img/companies/wolfssl-logo.jpg
Labels: content

#20 blog: add post about my porting of the feather-nrf52840
  Gemfile
  Gemfile.lock
  _config.yml
  _posts/2021-02-26-feather-nrf52840.md
  assets/css/main.scss
  assets/css/riot-code.css
  assets/img/blog/feather-nrf52840.jpg
Labels: blog, content

#63 fix: Update link to HiL nightlies
  index.html
Labels: content

#65 Fix colors and drivers list
  _sass/_general.scss
  _sass/pages/drivers.scss
  assets/css/main.scss
  drivers.html
Labels: bug, layout

#66 index: update links to boards, cpus, drivers
  index.html
Labels: content

#68 blog: add switch to hide and remove test posts
  README.md
  _config.yml
  _posts/2020-12-31-test-02.md
  _posts/2020-12-31-test-03.md
  _posts/2020-12-31-test.md
  index.html
Labels: blog, layout

#67 Gemfile.lock: update kramdown
  Gemfile.lock
Labels: enhancement

#70 _layouts/use-case: open company link in _blank
  _layouts/use-case.html
Labels: layout

#69 index: reword POSIX compliance
  index.html
Labels: content

#71 treewide: open external links in _blank
  _includes/driver_list.html
  _includes/social-media.html
  boards.html
  branding.html
  community.html
  contributors.html
  cpus.html
  drivers.html
  index.html
Labels: bug, content
