Repository RIOT-OS/riot-os.org, pull requests merged in 2021-02, with the labels that each got.

#6 gh_actions: configure to deploy using Github Pages
  .github/workflows/deployment.yml
  README.md
  _config.yml
  _config_development.yml
  _sass/_fonts.scss
  assets/css/main.scss
Labels: enhancement

#7 community: fix broken links to images
  community.html
Labels: bug

#8 README.md: Make README more easier to follow for ruby newcomers
  README.md
Labels: documentation, enhancement

#11 index: fix blog links
  index.html
Labels: bug

#16 community: fix email links
  community.html
Labels: bug

#19 Add cookies consent alert
  _includes/cookie-alert.html
  _layouts/base.html
  _sass/components/cookie-alert.scss
  _sass/pages/index.scss
  assets/css/main.scss
  assets/js/cookie-alert.js
  assets/js/main.js
  index.html
Labels: enhancement

#22 assets/vendor: include local jquery copy
  _layouts/base.html
  assets/vendor/jquery/jquery_2_1_1.min.js
Labels: cleanup

#23 includes/header: add missing 'scrollto' class
  _includes/header.html
Labels: bug
